# Generated by Django 5.0.3 on 2024-03-22 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baydenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_of_attendance',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
