# Generated by Django 5.0.2 on 2024-03-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baydenApp', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='job_title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
