# Generated by Django 5.0.2 on 2024-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baydenApp', '0003_attendee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='company_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
