# Generated by Django 5.0.2 on 2024-03-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baydenApp', '0004_attendee_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
